### ISSUE TITLE
add an admin action to export the waiting list as csv

### ISSUE THREAD

**Issue by jtauber** [pinax/pinax-waitinglist#16]
We have a management command but it would also be nice to add an admin action that does the same thing.

**Comment by dmhdev** [comment]
This would be my first contribution to open source, but I've implemented something similar on a few different projects. Mind if I work on this?

**Comment by KatherineMichel** [comment]
@vdaynm That would be great! Thank you for offering.

**Comment by dmhdev** [comment]
The existing management command exports the entire list. I can do the same, or only export selected entries. The second option makes more sense to me, do you have a preference?

**Comment by KatherineMichel** [comment]
@vdaynm I don't have a preference. I think you should go ahead and do the second option.

**Comment by KatherineMichel** [comment]
Closing thanks to #24! Thank you, @vdaynm!
