### ISSUE TITLE
Update AUTHORS page

### ISSUE THREAD

**Issue by jtauber** [pinax/pinax-waitinglist#3]
it's missing some contributors

**Comment by ossanna16** [comment]
@jtauber Could you provide a list of the people who are missing?

**Comment by jtauber** [comment]
The person doing this ticket can just look at the commits on this repo.

**Comment by ossanna16** [comment]
I think for issues with the "difficulty: easy" it would be great to provide 2 or 3 sentences explaining what needs to be done and where to look, that's why I asked :)
